### ISSUE TITLE
Filmstrip thumbnails cropped

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/wptagent#252] opened 2019-03-28 22:55 UTC
<img width="861" alt="Screen Shot 2019-03-29 at 11 42 58 AM" src="https://user-images.githubusercontent.com/204268/55197777-647b3680-5218-11e9-87ca-73b34d1dd965.png">

In the [second step](https://www.webpagetest.org/video/compare.php?tests=190328_QQ_e2795792a04a5aecc2ce2c210dca593d-r:1-c:0-s:2) of this scripted test the thumbnails are cropped to the wrong height. What's odd is that the first step has the right size thumbnail, so even though there's visual content changing in the second step it's being cropped off by the agent.

The [final screenshot](https://www.webpagetest.org/result/190328_QQ_e2795792a04a5aecc2ce2c210dca593d/1/screen_shot/#step_2) for the second step is at the right size though.

The issue seems specific to this particular scripted test. We're not seeing the issue with other tests.

**Comment by pmeenan** [comment] 2019-03-28 23:32
That usually happens when the orange div overlay over the page doesn't work which throws off the viewport calculation. Can you send me the script? I can try the overlay manually to see why it isn't working.


________________________________

**Comment by sean-roberts** [comment] 2019-03-29 14:32
```
// Login then navigate to URL
logData	0
speedcurve_removePTST	1
navigate	https://projects.invisionapp.com/d/login

sleep	4

setValue	id=emailAddress	seanroberts+speedcurve-3@invisionapp.com
exec	document.getElementById('emailAddress').dispatchEvent(new Event('change', {bubbles:true}))

setValue	id=password	REDACTED
exec	document.getElementById('password').dispatchEvent(new Event('change', {bubbles:true}))

sleep 2

exec	document.querySelector('form[method=POST].main-panel__form button.form__button').click()

// clear out any visual analysis
exec	document.body.innerHTML = ''
logData	1
navigate	https://projects.invisionapp.com/d/main
```

perhaps it has something to do with the `document.body.innerHTML = ''` line?

**Comment by pmeenan** [comment] 2019-03-29 14:38
Sorry, already sent Mark a reply out-of-band.  The issue is with the login step, it should be "execAndWait" instead of "exec".

```
execAndWAit	document.querySelector('form[method=POST].main-panel__form button.form__button').click()
```

THat way it waits for the login to actually complete before going on to the measurement.  Right now it is likely completing the login right in the middle of preparing for the next step.

**Comment by sean-roberts** [comment] 2019-03-29 14:45
Giving that a go now. 

Do I still need that clearing of innerHTML? My worry is that if I do it at the wrong point I will clear something in the HTML that should be getting measured

**Comment by sean-roberts** [comment] 2019-03-29 15:11
Yeah, my testing of these different options is getting worse results.

From your perspective, if I want to log in to a site and test the load time of the page that is redirected to, how should I go about testing that? All of the options I have experimented with either cause the test to fail entirely or start measuring too late.

Versions tried

1. the version that started this conversation, causes the strange viewport weirdness
```
exec	document.querySelector('form[method=POST].main-panel__form button.form__button').click()

// clear out any visual analysis
exec	document.body.innerHTML = ''
logData	1
navigate	https://projects.invisionapp.com/d/main
```
2. this version will complete the redirect and then reload, lots of things are already in cache
```
execAndWait	document.querySelector('form[method=POST].main-panel__form button.form__button').click()

// clear out any visual analysis
exec	document.body.innerHTML = ''
logData	1
navigate	https://projects.invisionapp.com/d/main
```

3. this version breaks doesn't capture any results at all.
```
execAndWait	document.querySelector('form[method=POST].main-panel__form button.form__button').click()

logData	1
```

**Comment by pmeenan** [comment] 2019-03-29 15:22
If you want to measure the actual login process and loading of the page you want to move the logData 1 to before the actual login action and get rid of the last navigate:

```
// Login then navigate to URL
logData	0
speedcurve_removePTST	1
navigate	https://projects.invisionapp.com/d/login

sleep	4

setValue	id=emailAddress	seanroberts+speedcurve-3@invisionapp.com
exec	document.getElementById('emailAddress').dispatchEvent(new Event('change', {bubbles:true}))

setValue	id=password	REDACTED
exec	document.getElementById('password').dispatchEvent(new Event('change', {bubbles:true}))

sleep 2

logData	1
execAndWait	document.querySelector('form[method=POST].main-panel__form button.form__button').click()
```

The wiping out of innerHTML before navigate isn't strictly necessary but it ensures that the visual metrics won't get tripped up by an animation on the previous page for example.

Chrome treats a navigation to the same URL as a reload which will cause some of what you are seeing with the second test.

THe third test doesn't log anything at all because recording isn't turned on.  The logData 1 command is what turns the recording back on but it isn't turned on until after the test is completed.

**Comment by sean-roberts** [comment] 2019-03-29 15:27
ugh... obviously 

heheh this is a new script added after an already long week. duh, navigation is going to start with the form POSTing.

Thanks for clearing up my Friday thinking on this.

**Comment by pmeenan** [comment] 2019-03-29 15:28
Sure, glad it got cleared up before the weekend so it wouldn't be bothering you the whole weekend :)

**Comment by sean-roberts** [comment] 2019-03-29 15:32
Hahah I am sure everyone worries about those things over the weekend, right? 😄

**Comment by pmeenan** [comment] 2019-03-29 16:33
Just checking to see if it looks like it is working as expected now. If so I'll close the issue.

**Comment by sean-roberts** [comment] 2019-03-29 17:33
Yep resolved 👍

**Closed** 2019-03-29 17:43 UTC
