### ISSUE TITLE
Inline SVG animation not show in filmstrip

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/wptagent#224] opened 2018-12-08 00:49 UTC
Hi Pat,

A bit stumped on this one. [This page](https://design.invisionapp.com/prototype/Member-Space-tour-cjl2ap281000wfk01ui220p25/play/7e64c1e7) has an inline SVG animation "in" that starts as soon as the HTML is downloaded when viewing in a browser.

But when [running a WPT test](https://www.webpagetest.org/video/compare.php?tests=181207_46_298fd995389cc60d2dd33b3cb6e7aff0-r:1-c:0) the animation is not shown even though there's a long 15s in the test after the HTML is downloaded and the main content is rendered. The CPU has plenty of downtime and blocking scripts/css don't seem to be in the way.

If I test in Lighthouse I do see the animation earlier in the Lighthouse filmstrip.

Is there any change the agent is not capturing the animation for some reason or am I missing something in the page that's blocking it from rendering? Even if I throttle my local machine right down I still get the animation as soon as HTML arrives.

**Comment by pmeenan** [comment] 2018-12-08 01:01
Try passing keepvideo=1 as a test option to grab the raw video. That will show if the animation is getting dropped by the video processing or if it's not captured.


________________________________

**Comment by zeman** [comment] 2018-12-09 23:35
The raw video shows the animation is present.

https://drive.google.com/file/d/1Q5lrysK2Pgao5SHyuYgMkYUGK5nXpgrk/view?usp=sharing

Interestingly the animation does show correctly if mobile emulation is turned on.

https://www.webpagetest.org/video/compare.php?tests=181209_3E_7d4ed5df24957f060c8d6a3228d0b299-r:1-c:0

**Comment by pmeenan** [comment] 2018-12-10 14:38
The animation takes a larger % of the screen in mobile which is probably what makes the difference. Current guess is that the threshold for start render in the video processing is requiring too significant of a change and isn't detecting the smaller icon. Looking now to see exactly what is tripping it.

**Comment by pmeenan** [comment] 2018-12-10 14:49
Should be fixed now. The start render detection required 500 pixels to have at least a 10% change. I dropped it down to 0 which is what most of the change code uses.

**Comment by sean-roberts** [comment] 2018-12-10 18:09
Is this susceptible to the "Waiting for..." dialogs at the bottom of the screen to trigger a start render metric?
For example, this is saying start render has happened:

![xtest](https://user-images.githubusercontent.com/950274/49751906-b0f83180-fc7c-11e8-95e5-ba68e2c2d30d.jpeg)

**Comment by pmeenan** [comment] 2018-12-10 18:11
It shouldn't have been since there are supposed to be margins that are ignored around the border. Can you send me a sample test where you're seeing issues? It's possible the margins aren't correct.

**Comment by sean-roberts** [comment] 2018-12-10 19:47
Here is a page test I just ran: https://www.webpagetest.org/result/181210_1G_fcc551e137edfa0b6046c96f3a8f5da8/

And here is one I ran from SC that sent me on this hunt
https://wpt1.speedcurve.com/video/compare.php?tests=181210_ZB_e4a82d102e4572743e7110b887f3a639-r:1-c:0

**Comment by pmeenan** [comment] 2018-12-10 19:50
Sorry, I meant if you have any where the start render is now being detected too early (the "waiting for..."). As far as I can tell, the one you just ran worked correctly.  If there are cases where the status bar triggers an early detection I'll need to look at those videos to see why the bar wasn't ignored.

**Comment by sean-roberts** [comment] 2018-12-10 19:51
check the one from speedcurve

**Comment by sean-roberts** [comment] 2018-12-10 19:51
I am running another test right now with emulated dimensions

**Comment by pmeenan** [comment] 2018-12-10 19:53
Thanks, trying to reproduce it myself as well.

**Comment by pmeenan** [comment] 2018-12-10 19:54
Reproduced it with the raw video capture so I can run it through the processing and see why it triggered: https://www.webpagetest.org/result/181210_BT_fe42e27b063782ec0d265a21a2b536b3/

**Comment by sean-roberts** [comment] 2018-12-10 19:55
ok excellent, let me know if you need anything else from me

**Comment by pmeenan** [comment] 2018-12-10 20:07
Just pushed a fix. Should roll out over the next hour.

**Comment by pmeenan** [comment] 2018-12-10 21:21
Argh. Forgot to actually push it to the release branch which is what gets picked up by the running agents. Will take up to another hour to roll out

**Comment by pmeenan** [comment] 2018-12-11 15:04
Should be working correctly now. Feel free to re-open if any more issues crop up: https://www.webpagetest.org/result/181211_5B_2d5c359d6ad254533d1c027bdea6626e/

**Closed by pmeenan** 2018-12-11 15:04 UTC

**Comment by zeman** [comment] 2018-12-12 00:09
Thanks for sorting that out Pat!

**Comment by sean-roberts** [comment] 2019-01-23 16:43
@pmeenan @zeman 

On SpeedCurve: https://wpt1.speedcurve.com/video/compare.php?tests=190123_E4_baed4d100325d4b9b8ed10a0a1fb52b5-r:3-c:0

On WPT.org: https://wpt1.speedcurve.com/video/compare.php?tests=190123_E4_baed4d100325d4b9b8ed10a0a1fb52b5-r:3-c:0

The SpeedCurve run has stopped seeing the loading indicator again and jumped our start render time reporting. Which I believe is because that's what WPT was reporting. Was there a change that has not made it to SpeedCurve yet?

**Comment by pmeenan** [comment] 2019-01-24 22:38
If you run a test with keepvideo=1 you will get the raw mp4 of the video capture. I then run those through the visualmetrics script which is what does all of the frame extraction/de-duping/etc.  Odds are it was rendered but visualmetrics thought the change was too small to consider a changed frame (the tolerance should be really tight for the first/last frames so that's a bit surprising).

**Comment by wildlyinaccurate** [comment] 2019-01-24 23:59
I don't have the raw video yet but I have just noticed that for the SpeedCurve test that @sean-roberts linked, we have no frames between 0s and 16.2s, which seems to confirm your theory about visualmetrics thinking the change is too small.

The thing I haven't quite figured out is the disparity between wpt.org and SpeedCurve. Does wpt.org use a higher framerate than the default of 10 fps?

It would be good if wptagent propagated its verbose-ness to visualmetrics so that debug=1 enabled verbose output from visualmetrics. Should I submit a patch for that or do you think that would add too much noise to the logs?

**Comment by pmeenan** [comment] 2019-01-25 00:05
WPT uses the default 10fps as well. You use a higher resolution than the default 1024x768, don't you?

Visualmetrics is run as a subprocess and the output isn't logged. Getting the logging would require capturing the output (I think) or calling the code directly in a thread.


________________________________
